name: GCP Docker Push

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-west1
  GAR_LOCATION: europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mon-repo-docker
  API_IMAGE: medical-chatbot-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run evaluation
        run: |
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install transformers peft accelerate safetensors requests
          python test_CI/eval_model.py

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/934256576698/locations/global/workloadIdentityPools/github-pool/providers/github
          service_account: github-actions-deploy@project-51e18c68-41e7-4d2d-a72.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Verify gcloud auth
        run: |
          gcloud config set project ${{ env.PROJECT_ID }}
          gcloud auth list
          gcloud config get-value project

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Build API Docker Image
        run: |
          docker build \
            -t ${{ env.GAR_LOCATION }}/${{ env.API_IMAGE }}:${{ github.sha }} \
            -t ${{ env.GAR_LOCATION }}/${{ env.API_IMAGE }}:latest \
            ./api

      - name: Push API Docker Image
        run: |
          docker push ${{ env.GAR_LOCATION }}/${{ env.API_IMAGE }}:${{ github.sha }}
          docker push ${{ env.GAR_LOCATION }}/${{ env.API_IMAGE }}:latest